version: "3.9"

services:
  ai_model:
    build: ../ai_model
    container_name: ai_model
    ports:
      - "8001:8000"

  backend:
    build: ../backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - ai_model

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
